name: DAST

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up OWASP ZAP
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: 'https://verifacts.co.in/'
          token: ${{ secrets.ZAP_TOKEN }}
          filters: '-exclude=http://your-app-url/some-excluded-path'

      - name: Upload ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html
